name: Git It Sync Tests

on:
  push:
    branches: [ main, master, develop, 'claude/**' ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, mbstring, zip
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Check PHP syntax errors
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Run PHPUnit tests
        run: composer test

      - name: Validate plugin file exists
        run: test -f git-it-write.php && echo "Plugin file found"
